/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PizzaControl;
import dto.PizzaDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Italo
 */
public class Criar_pizza extends javax.swing.JFrame {

    /**
     * Creates new form Criar_pizza
     */
    private Abrir_pedido tela;
    private PizzaControl pizzaControl;

    public Criar_pizza(Abrir_pedido telaPedidos) {
        initComponents();
        tela = telaPedidos;
        pizzaControl = new PizzaControl();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNomePizza = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblQuantFatias = new javax.swing.JTextField();
        txtValorPizza = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboS1 = new javax.swing.JComboBox<>();
        comboS2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Insira os dados da pizza"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome");

        lblNomePizza.setEditable(false);
        lblNomePizza.setText("Moda do cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Quant. fatias");

        lblQuantFatias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantFatias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblQuantFatiasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblQuantFatiasKeyReleased(evt);
            }
        });

        txtValorPizza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtValorPizza.setText(" ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Sabor 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Sabor 2");

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_save_2639912.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Valor R$");

        comboS1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Queijo", "Frango", "Calabresa", "Presunto", "Gorgonzola" }));

        comboS2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gorgonzola", "Queijo", "Frango", "Calabresa", "Presunto" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNomePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantFatias)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtValorPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 33, Short.MAX_VALUE)))))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(comboS2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(comboS1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btSalvar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNomePizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblQuantFatias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(comboS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(323, 368));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblQuantFatiasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblQuantFatiasKeyReleased
        try {
            if (lblQuantFatias.getText().length() > 0) {
                int quantFatias = Integer.parseInt((String) lblQuantFatias.getText());
                double valorPizza = ((quantFatias * 2) * 2) + 20;
                txtValorPizza.setText(String.valueOf(valorPizza));
            }
            if (lblQuantFatias.getText().length() == 0) {
                txtValorPizza.setText("Valor R$");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite apenas número.");
        }


    }//GEN-LAST:event_lblQuantFatiasKeyReleased

    private void lblQuantFatiasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblQuantFatiasKeyPressed

    }//GEN-LAST:event_lblQuantFatiasKeyPressed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        try {
            String sabor1 = comboS1.getSelectedItem().toString();
            String sabor2 = comboS2.getSelectedItem().toString();

            if (lblQuantFatias.getText().length() > 0 && sabor1.length() > 0 && sabor2.length() > 0) {

                String[] sabores = {sabor1, sabor2};
                String nome = lblNomePizza.getText();
                double valor = Double.parseDouble((String) txtValorPizza.getText());
                int quant_fatias = Integer.parseInt((String) lblQuantFatias.getText());

                PizzaDTO pizzaDto = new PizzaDTO();
                pizzaDto.setNome(nome);
                pizzaDto.setValor(valor);
                pizzaDto.setQuant_fatias(quant_fatias);
                pizzaDto.setSabores(sabores);
                pizzaDto.setTamanho("Personalizada");
                pizzaDto.setFatia(0);

                // RETORNA O ID DA PIZZA QUE FOI CADASTRADA.
                int id = pizzaControl.salvaPizzaPersonalizada(pizzaDto);
                if (id != 0) {
                    this.tela.setaDadosPizza(nome, valor + "", quant_fatias + "", id + "", "Personalizada");
                    dispose();
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro." + e.getMessage());
        }

    }//GEN-LAST:event_btSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> comboS1;
    private javax.swing.JComboBox<String> comboS2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblNomePizza;
    private javax.swing.JTextField lblQuantFatias;
    private javax.swing.JLabel txtValorPizza;
    // End of variables declaration//GEN-END:variables
}
