/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.*;
import dto.PizzaDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Italo
 */
public class Escolher_pizza extends javax.swing.JFrame {

    /**
     * Creates new form Escolher_pizza
     */
    private PizzaControl pizzaControl;
    private Abrir_pedido tela;

    public Escolher_pizza(Abrir_pedido telaAtual) {
        initComponents();
        pizzaControl = new PizzaControl();
        tela = telaAtual;
        preenchertabela();
    }

    private void preenchertabela() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        try {
            PizzaDTO pizzaSelecionada = pizzaControl.listarPizza();
            
            for (PizzaDTO x : pizzaSelecionada.getPizzasCadastradas()) {
                String[] dados = new String[5];
                dados[0] = x.getNome();
                dados[1] = x.getTamanho();
                dados[2] = x.getQuant_fatias()+"";
                dados[3] = x.getValor()+"";
                dados[4] = x.getId() + "";
                model.addRow(dados);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btEscolher = new javax.swing.JButton();
        btVerSabores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tamanho", "Quant. fatias", "Valor", "ID"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btEscolher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEscolher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_f-check_256_282474.png"))); // NOI18N
        btEscolher.setText("Escolher");
        btEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscolherActionPerformed(evt);
            }
        });

        btVerSabores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btVerSabores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_Food_C219_2427861.png"))); // NOI18N
        btVerSabores.setText("Ingredientes");
        btVerSabores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerSaboresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btEscolher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btVerSabores)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEscolher)
                    .addComponent(btVerSabores))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(424, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscolherActionPerformed
        // TODO add your handling code here:
        int linha = tabela.getSelectedRow();
        if (linha != -1) {
            String nome = (String) tabela.getValueAt(linha, 0);
            String tamanho = (String) tabela.getValueAt(linha, 1);
            String valor = (String) tabela.getValueAt(linha, 2);
            String quant_fatias = (String) tabela.getValueAt(linha, 3);
            String id = (String) tabela.getValueAt(linha, 4);
            tela.setaDadosPizza(nome, valor, quant_fatias, id, tamanho);
            if (nome.length() > 0 && tamanho.length() > 0 && id.length() > 0) {
                dispose();
            }
        }
    }//GEN-LAST:event_btEscolherActionPerformed
    private void btVerSaboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerSaboresActionPerformed
        ArrayList<String> sabores = new ArrayList<String>();
        try {
            int linha = tabela.getSelectedRow();
            if (linha != -1) {
                int id = Integer.parseInt((String) tabela.getValueAt(linha, 4));
                sabores = pizzaControl.verSabores(id);
                JOptionPane.showMessageDialog(null, sabores.toArray());
               
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btVerSaboresActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEscolher;
    private javax.swing.JButton btVerSabores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
