/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Italo
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    private String fLogado;

    public Inicial(String logado) {
        initComponents();

        verificaFuncionario(logado);
        setaData();
        fLogado = logado;
        lblFuncionarioLogado.setText(logado);
        iniciarHora();
    }

    private void iniciarHora() {
        Thread relogio = new Thread(new Inicial.horaThread());
        relogio.start();
    }

    private void setaData() {
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        Date dataAtual = new Date(System.currentTimeMillis());
        lblData.setText("Data \n" + formatador.format(dataAtual));

    }

    private void verificaFuncionario(String cargo) {
        if (cargo.equalsIgnoreCase("atendente")) {
            this.barra_menu.setVisible(false);
            btpedidosAentregar.setEnabled(false);
        } else if (cargo.equalsIgnoreCase("pizzaiolo")) {
            this.barra_menu.setVisible(false);
            btCadastrarCliente.setEnabled(false);
            btNovoPedid.setEnabled(false);
            btpedidosAentregar.setEnabled(false);

        } else if (cargo.equalsIgnoreCase("motoboy")) {
            this.barra_menu.setVisible(false);
            btPedidos.setEnabled(false);
            btCadastrarCliente.setEnabled(false);
            btNovoPedid.setEnabled(false);
        }
    }

    class horaThread implements Runnable {

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

        @Override
        public void run() {
            while (true) {
                lblHora.setText("Hora: " + sdf.format(new java.util.Date()));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao exibir hora");
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        PainelPrincipal = new javax.swing.JPanel();
        areaDeTrabalho = new javax.swing.JDesktopPane();
        painel_botoes = new javax.swing.JPanel();
        btCadastrarCliente = new javax.swing.JButton();
        btNovoPedid = new javax.swing.JButton();
        btPedidos = new javax.swing.JButton();
        btpedidosAentregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblFuncionarioLogado = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        barra_menu = new javax.swing.JMenuBar();
        menu_cadastro = new javax.swing.JMenu();
        op_cadastrarCliente = new javax.swing.JMenuItem();
        op_cadastrarFuncionari = new javax.swing.JMenuItem();
        op_cadastrarPizza = new javax.swing.JMenuItem();
        menu_registro = new javax.swing.JMenu();
        clientes_cadastrados = new javax.swing.JMenuItem();
        funcionarios_cadastrados = new javax.swing.JMenuItem();
        pizzas_cadastradas = new javax.swing.JMenuItem();
        menu_contabilidades = new javax.swing.JMenu();
        op_vendas = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);

        areaDeTrabalho.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painel_botoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_add_user_309049.png"))); // NOI18N
        btCadastrarCliente.setText("Cliente");
        btCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarClienteActionPerformed(evt);
            }
        });

        btNovoPedid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_notepad_285631.png"))); // NOI18N
        btNovoPedid.setText("Pedido");
        btNovoPedid.setPreferredSize(new java.awt.Dimension(113, 42));
        btNovoPedid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoPedidActionPerformed(evt);
            }
        });

        btPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_thefreeforty_register_1243707.png"))); // NOI18N
        btPedidos.setText("Lista");
        btPedidos.setPreferredSize(new java.awt.Dimension(113, 42));
        btPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosActionPerformed(evt);
            }
        });

        btpedidosAentregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_thefreeforty_register_1243707.png"))); // NOI18N
        btpedidosAentregar.setText("Espera");
        btpedidosAentregar.setPreferredSize(new java.awt.Dimension(113, 42));
        btpedidosAentregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpedidosAentregarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Acesso rápido");

        javax.swing.GroupLayout painel_botoesLayout = new javax.swing.GroupLayout(painel_botoes);
        painel_botoes.setLayout(painel_botoesLayout);
        painel_botoesLayout.setHorizontalGroup(
            painel_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_botoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painel_botoesLayout.createSequentialGroup()
                        .addGroup(painel_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCadastrarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btNovoPedid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btpedidosAentregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painel_botoesLayout.setVerticalGroup(
            painel_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_botoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btNovoPedid, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btpedidosAentregar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btSair.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_exit_2639810.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setPreferredSize(new java.awt.Dimension(113, 42));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuário logado");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblFuncionarioLogado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFuncionarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFuncionarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                .addComponent(areaDeTrabalho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addComponent(painel_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(areaDeTrabalho)
        );

        menu_cadastro.setText("Cadastro");

        op_cadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        op_cadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_9_2698684.png"))); // NOI18N
        op_cadastrarCliente.setText("Cliente");
        op_cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_cadastrarClienteActionPerformed(evt);
            }
        });
        menu_cadastro.add(op_cadastrarCliente);

        op_cadastrarFuncionari.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        op_cadastrarFuncionari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_9_2698684.png"))); // NOI18N
        op_cadastrarFuncionari.setText("Funcionário");
        op_cadastrarFuncionari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_cadastrarFuncionariActionPerformed(evt);
            }
        });
        menu_cadastro.add(op_cadastrarFuncionari);

        op_cadastrarPizza.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        op_cadastrarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_Food_C219_2427861.png"))); // NOI18N
        op_cadastrarPizza.setText("Pizza");
        op_cadastrarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_cadastrarPizzaActionPerformed(evt);
            }
        });
        menu_cadastro.add(op_cadastrarPizza);

        barra_menu.add(menu_cadastro);

        menu_registro.setText("Registro");

        clientes_cadastrados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        clientes_cadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_9_2698684.png"))); // NOI18N
        clientes_cadastrados.setText("Clientes");
        clientes_cadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes_cadastradosActionPerformed(evt);
            }
        });
        menu_registro.add(clientes_cadastrados);

        funcionarios_cadastrados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        funcionarios_cadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_9_2698684.png"))); // NOI18N
        funcionarios_cadastrados.setText("Funcionários");
        funcionarios_cadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarios_cadastradosActionPerformed(evt);
            }
        });
        menu_registro.add(funcionarios_cadastrados);

        pizzas_cadastradas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        pizzas_cadastradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_Food_C219_2427861.png"))); // NOI18N
        pizzas_cadastradas.setText("Pizzas");
        pizzas_cadastradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzas_cadastradasActionPerformed(evt);
            }
        });
        menu_registro.add(pizzas_cadastradas);

        barra_menu.add(menu_registro);

        menu_contabilidades.setText("Contabilidade");

        op_vendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        op_vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_money_172506.png"))); // NOI18N
        op_vendas.setText("Vendas realizadas");
        op_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_vendasActionPerformed(evt);
            }
        });
        menu_contabilidades.add(op_vendas);

        barra_menu.add(menu_contabilidades);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(789, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);

        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarClienteActionPerformed
        // TODO add your handling code here:
        Cadastro_cliente cadastro = new Cadastro_cliente();
        this.areaDeTrabalho.add(cadastro);
        cadastro.setVisible(true);
        cadastro.setPosicao();
    }//GEN-LAST:event_btCadastrarClienteActionPerformed

    private void op_cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_cadastrarClienteActionPerformed
        // TODO add your handling code here:
        Cadastro_cliente cadastro = new Cadastro_cliente();
        this.areaDeTrabalho.add(cadastro);
        cadastro.setVisible(true);
        cadastro.setPosicao();
    }//GEN-LAST:event_op_cadastrarClienteActionPerformed

    private void op_cadastrarFuncionariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_cadastrarFuncionariActionPerformed
        // TODO add your handling code here:
        Cadastro_funcionario cadastro = new Cadastro_funcionario();
        this.areaDeTrabalho.add(cadastro);
        cadastro.setVisible(true);
        cadastro.setPosicao();
    }//GEN-LAST:event_op_cadastrarFuncionariActionPerformed

    private void op_cadastrarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_cadastrarPizzaActionPerformed
        // TODO add your handling code here:
        Cadastro_pizza cadastro = new Cadastro_pizza();
        this.areaDeTrabalho.add(cadastro);
        cadastro.setVisible(true);
        cadastro.setPosicao();
    }//GEN-LAST:event_op_cadastrarPizzaActionPerformed

    private void clientes_cadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes_cadastradosActionPerformed
        // TODO add your handling code here:
        Cliente_cadastrados registro = new Cliente_cadastrados();
        areaDeTrabalho.add(registro);
        registro.setVisible(true);
        registro.setPosicao();
    }//GEN-LAST:event_clientes_cadastradosActionPerformed

    private void funcionarios_cadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarios_cadastradosActionPerformed
        // TODO add your handling code here:
        Funcionarios_cadastrados registro = new Funcionarios_cadastrados();
        areaDeTrabalho.add(registro);
        registro.setVisible(true);
        registro.setPosicao();
    }//GEN-LAST:event_funcionarios_cadastradosActionPerformed

    private void pizzas_cadastradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzas_cadastradasActionPerformed
        // TODO add your handling code here:
        Pizzas_cadastradas registro = new Pizzas_cadastradas();
        areaDeTrabalho.add(registro);
        registro.setVisible(true);
        registro.setPosicao();
    }//GEN-LAST:event_pizzas_cadastradasActionPerformed

    private void btNovoPedidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoPedidActionPerformed
        // TODO add your handling code here:
        Abrir_pedido pedido = new Abrir_pedido();
        areaDeTrabalho.add(pedido);
        pedido.setVisible(true);
        pedido.setPosicao();
    }//GEN-LAST:event_btNovoPedidActionPerformed

    private void op_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_vendasActionPerformed
        // TODO add your handling code here:
        Vendas_realizadas vendas = new Vendas_realizadas();
        areaDeTrabalho.add(vendas);
        vendas.setVisible(true);
        vendas.setPosicao();
    }//GEN-LAST:event_op_vendasActionPerformed

    private void btPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosActionPerformed
        // TODO add your handling code here:
        new Tela_pizzaiolo(fLogado).setVisible(true);
    }//GEN-LAST:event_btPedidosActionPerformed

    private void btpedidosAentregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpedidosAentregarActionPerformed
        // TODO add your handling code here:
        new Tela_motoboy().setVisible(true);
    }//GEN-LAST:event_btpedidosAentregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JDesktopPane areaDeTrabalho;
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JButton btCadastrarCliente;
    private javax.swing.JButton btNovoPedid;
    private javax.swing.JButton btPedidos;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btpedidosAentregar;
    private javax.swing.JMenuItem clientes_cadastrados;
    private javax.swing.JMenuItem funcionarios_cadastrados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFuncionarioLogado;
    private javax.swing.JLabel lblHora;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenu menu_contabilidades;
    private javax.swing.JMenu menu_registro;
    private javax.swing.JMenuItem op_cadastrarCliente;
    private javax.swing.JMenuItem op_cadastrarFuncionari;
    private javax.swing.JMenuItem op_cadastrarPizza;
    private javax.swing.JMenuItem op_vendas;
    private javax.swing.JPanel painel_botoes;
    private javax.swing.JMenuItem pizzas_cadastradas;
    // End of variables declaration//GEN-END:variables
}
