/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PizzaControl;
import dto.PizzaDTO;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pizza;

/**
 *
 * @author Italo
 */
public class Pizzas_cadastradas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pizzas_cadastradas
     */
    private PizzaControl pizzaControl;

    public Pizzas_cadastradas() {
        initComponents();
        pizzaControl = new PizzaControl();
        preenchertabela();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private void preenchertabela() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        try {
            PizzaDTO pizzasDto = pizzaControl.listarPizza();

            for (PizzaDTO x : pizzasDto.getPizzasCadastradas()) {
                String[] dados = new String[6];
                dados[0] = x.getNome();
                dados[1] = x.getTamanho();
                dados[2] = x.getValor() + "";
                dados[3] = x.getFatia() + "";
                dados[4] = x.getQuant_fatias() + "";
                dados[5] = x.getId() + "";
                model.addRow(dados);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void atualizartabela() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setNumRows(0);
        try {
            PizzaDTO pizzasDto = pizzaControl.listarPizza();

            for (PizzaDTO x : pizzasDto.getPizzasCadastradas()) {
                String[] dados = new String[6];
                dados[0] = x.getNome();
                dados[1] = x.getTamanho();
                dados[2] = x.getValor() + "";
                dados[3] = x.getFatia() + "";
                dados[4] = x.getQuant_fatias() + "";
                dados[5] = x.getId() + "";
                model.addRow(dados);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btVerSabores = new javax.swing.JButton();

        setClosable(true);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tamanho", "Valor", "Valor da fatia", "Quant. fatias", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_ic_delete_48px_352303.png"))); // NOI18N
        btExcluir.setText("Excluir pizza");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btVerSabores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btVerSabores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/iconfinder_Food_C219_2427861.png"))); // NOI18N
        btVerSabores.setText("Ingredientes");
        btVerSabores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerSaboresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVerSabores, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btVerSabores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setBounds(0, 0, 613, 481);
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tabela.getSelectedRow();
        if (linha != -1) {
            int idPizza = Integer.parseInt((String) tabela.getValueAt(linha, 5));
            try {
                if (pizzaControl.excluirPizza(idPizza)) {
                    JOptionPane.showMessageDialog(null, "Registro excluído.");
                    atualizartabela();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btVerSaboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerSaboresActionPerformed
        ArrayList<String> sabores = new ArrayList<String>();
        try {
            int linha = tabela.getSelectedRow();
            if (linha != -1) {
                int id = Integer.parseInt((String) tabela.getValueAt(linha, 5));
                sabores = pizzaControl.verSabores(id);
                JOptionPane.showMessageDialog(null, sabores.toArray());

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btVerSaboresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btVerSabores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
