/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PedidoControl;
import dto.PedidoDTO;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pedido;
import model.Pizza;

/**
 *
 * @author Italo
 */
public class Vendas_realizadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendas_realizadas
     */
    private PedidoControl pedidoControl;

    public Vendas_realizadas() {
        initComponents();
        pedidoControl = new PedidoControl();
        preencherTabela();
        calculaTotal();
    }

    private void calculaTotal() {
        double total = 0;
        if (tabela.getRowCount() > 0) {
            for (int i = 0; i < tabela.getRowCount(); i++) {
                total += Double.parseDouble((String) tabela.getValueAt(i, 3));
            }
            txtTotal.setText("Total R$: " + total + "");
        }

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        txtTotal = new javax.swing.JLabel();

        setClosable(true);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Pizza", "Tamanho", "Valor", "ID"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        setBounds(0, 0, 537, 365);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {
        try {
            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            PedidoDTO pedidosDTO = pedidoControl.listarPedidos();
            for (PedidoDTO x : pedidosDTO.getPedidosCadastrados()) {
                String[] dados = new String[5];
                dados[0] = x.getCliente().getNome();
                dados[1] = x.getPizza().getNome();
                dados[2] = x.getPizza().getTamanho();
                dados[3] = x.getPizza().getValor() + "";
                dados[4] = x.getId() + "";
                model.addRow(dados);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
